# Generated by Django 2.2 on 2019-04-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='submittime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间'),
        ),
    ]
