# Generated by Django 2.2 on 2019-04-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='examname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='考试科目'),
        ),
    ]
