# Generated by Django 2.1.7 on 2019-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190407_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='submittime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
