# Generated by Django 2.2 on 2019-04-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_student_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='msg',
        ),
        migrations.AddField(
            model_name='class',
            name='msg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='消息通知'),
        ),
    ]
