# Generated by Django 2.2 on 2019-04-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190424_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='exam_title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='在考科目'),
        ),
    ]
