# Generated by Django 2.2 on 2019-04-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Examtitle', models.CharField(default='', max_length=50, verbose_name='考试名称')),
                ('Examstarttime', models.DateTimeField(verbose_name='考试开始时间')),
                ('is_auto', models.BooleanField(default=False, verbose_name='自动开始')),
                ('Examstatus', models.IntegerField(choices=[(-1, '已结束'), (0, '未开始'), (1, '已开始')], default=0, verbose_name='考试状态')),
            ],
            options={
                'verbose_name': '考试信息',
                'verbose_name_plural': '考试信息',
                'db_table': 'teacher_examinfo',
            },
        ),
    ]
