# Generated by Django 2.2 on 2019-04-22 21:35

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filename', models.CharField(max_length=100, verbose_name='文件名')),
                ('Filedata', models.BinaryField(max_length=builtins.max, verbose_name='文件内容')),
                ('Filesize', models.CharField(max_length=100, verbose_name='文件大小')),
                ('Filetime', models.DateTimeField(auto_now=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '提交文件信息',
                'verbose_name_plural': '提交文件信息',
                'db_table': 'student_file',
            },
        ),
    ]
