# Generated by Django 2.2 on 2019-04-18 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='Filetime',
            field=models.DateField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='files',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Student', to_field='user_id', verbose_name='学号'),
        ),
    ]
