# Generated by Django 2.2 on 2019-04-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20190418_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='Filetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
    ]
