# Generated by Django 2.2 on 2019-04-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20190418_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='Filetime',
            field=models.DateTimeField(auto_now=True, verbose_name='上传时间'),
        ),
    ]
