# Generated by Django 2.2 on 2019-04-18 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_auto_20190418_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Student', verbose_name='学号'),
        ),
    ]
