# Generated by Django 2.2 on 2019-04-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_auto_20190418_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='Filesize',
            field=models.CharField(max_length=100, verbose_name='文件大小'),
        ),
    ]
